name: Create Release and Build Artifacts

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Type of release'
        required: true
        options:
        - patch
        - minor
        - major

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.semver.outputs.new_tag }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.release_type }}
          WITH_V: true
          DRY_RUN: false

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          name: ${{ steps.semver.outputs.new_tag }}
          tag_name: ${{ steps.semver.outputs.new_tag }}

  build_and_push:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: gabrielbiasi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            gabrielbiasi/my-app:${{ needs.create_release.outputs.new_tag }}
            gabrielbiasi/my-app:latest

      - name: Package Helm chart
        run: |
          helm package ./my-app --version ${{ needs.create_release.outputs.new_tag }}

      - name: Upload Helm chart
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./my-app-${{ needs.create_release.outputs.new_tag }}.tgz
          asset_name: my-app-${{ needs.create_release.outputs.new_tag }}.tgz
          asset_content_type: application/gzip

  deploy_to_kubernetes:
    needs: [create_release, build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Spinnaker CLI
        run: |
          curl -LO https://storage.googleapis.com/spinnaker-artifacts/spin/$(curl -s https://storage.googleapis.com/spinnaker-artifacts/spin/latest)/linux/amd64/spin
          chmod +x spin
          sudo mv spin /usr/local/bin/spin

      - name: Authenticate with Spinnaker
        run: |
          echo "${{ secrets.SPINNAKER_CONFIG }}" > ~/.spin/config
        env:
          SPINNAKER_CONFIG: ${{ secrets.SPINNAKER_CONFIG }}

      - name: Trigger Spinnaker Pipeline
        run: |
          spin pipeline execute \
            --name my-pipeline \
            --application my-app \
            --parameter version=${{ needs.create_release.outputs.new_version }} \
            --parameter chartUrl=https://github.com/${{ github.repository }}/releases/download/${{ needs.create_release.outputs.new_version }}/my-app-${{ needs.create_release.outputs.new_version }}.tgz
